In [1]:
from selenium import webdriver 
import time as TIME
import pandas as pd
import datetime 


import warnings
warnings.filterwarnings("ignore")

In [2]:
def get_data(url):
    data_element = browser.find_elements_by_xpath(url)
    datas = [x.text for x in data_element]
    return datas

In [4]:
option = webdriver.ChromeOptions()

option.add_argument("â€” incognito")

executable_path = "/Users/cuong/Documents/Selenium/chromedriver"
#executable_path = "C:\\Users\\truon\\Downloads\\chromedriver_win32\\chromedriver"

browser = webdriver.Chrome(executable_path = executable_path, 
                            chrome_options=option)

browser.get("https://trade-hn.vndirect.com.vn/chung-khoan/phai-sinh")


TIME.sleep(5)

In [5]:
columns = ["Time","Price", "Change","Volume","CumVol"]

df = pd.DataFrame(columns = columns)

start_time = TIME.time()

date = get_data("//*[@id='clock-date']")

#browser.find_element_by_xpath("//*[@id='banggia-phaisinh-body']/tr[2]/td[1]").click()

#TIME.sleep(2)
i = 1

while True:
    try:
        
        time = get_data("//*[@id='derivative-info-body-VN30F1810']/div/div[" + str(i) + "]/span[1]")
 
        price = get_data("//*[@id='derivative-info-body-VN30F1810']/div/div[" + str(i) + "]/span[2]")
        change = get_data("//*[@id='derivative-info-body-VN30F1810']/div/div[" + str(i) + "]/span[3]")
        vol = get_data("//*[@id='derivative-info-body-VN30F1810']/div/div[" + str(i) + "]/span[4]")
        cumvol = get_data("//*[@id='derivative-info-body-VN30F1810']/div/div[" + str(i) + "]/span[5]")
        
        if change == ['']:
            change = ['0']

            
        df.loc[i-1] = (time[0], price[0], change[0], vol[0], cumvol[0])
        #print(i, time, price, change, vol, cumvol)
        i += 1
        
    except:
        print("                       Mission Accomplished")
        print("--- %s seconds ---" % (TIME.time() - start_time))
        break

df = df.iloc[::-1].reset_index(drop = True)

                       Mission Accomplished
--- 300.2520909309387 seconds ---

In [6]:
df

          Time  Price Change Volume   CumVol
0     09:00:06  925.0      6    903      903
1     09:00:18  925.5    6.5     35      938
2     09:00:28  925.5    6.5     71    1,009
3     09:00:29  925.5    6.5     15    1,024
4     09:00:33  925.0      6     55    1,079
5     09:00:55  925.1    6.1    248    1,327
6     09:01:03  925.0      6     79    1,406
7     09:01:05  925.0      6      2    1,408
8     09:01:19  925.0      6     71    1,479
9     09:01:37  925.0      6     71    1,550
10    09:01:50  925.0      6     33    1,583
11    09:01:51  924.7    5.7     10    1,593
12    09:01:53  924.7    5.7     18    1,611
13    09:01:56  924.8    5.8     34    1,645
14    09:02:09  924.8    5.8     17    1,662
15    09:02:28  924.9    5.9     62    1,724
16    09:02:28  924.9    5.9     13    1,737
17    09:02:34  925.0      6     12    1,749
18    09:02:56  925.3    6.3     74    1,823
19    09:03:03  925.5    6.5     71    1,894
20    09:03:12  925.6    6.6     83    1,977
21    09:03:17  925.8    6.8     28    2,005
22    09:03:30  925.6    6.6    104    2,109
23    09:03:43  925.5    6.5     77    2,186
24    09:03:44  925.5    6.5     15    2,201
25    09:03:48  925.5    6.5      6    2,207
26    09:03:58  926.0      7     83    2,290
27    09:04:10  926.0      7     38    2,328
28    09:04:19  926.0      7     51    2,379
29    09:04:20  925.8    6.8      5    2,384
...        ...    ...    ...    ...      ...
1385  14:24:56  936.7   17.7     88  113,734
1386  14:25:15  936.8   17.8     34  113,768
1387  14:25:25  936.7   17.7     79  113,847
1388  14:25:40  937.0     18    196  114,043
1389  14:25:45  937.0     18     53  114,096
1390  14:26:01  937.3   18.3    170  114,266
1391  14:26:11  937.5   18.5    141  114,407
1392  14:26:30  937.3   18.3    161  114,568
1393  14:26:49  937.2   18.2    146  114,714
1394  14:27:02  936.9   17.9    355  115,069
1395  14:27:05  936.7   17.7     19  115,088
1396  14:27:07  936.7   17.7     16  115,104
1397  14:27:10  936.7   17.7     69  115,173
1398  14:27:13  936.7   17.7     27  115,200
1399  14:27:17  936.6   17.6     49  115,249
1400  14:27:23  936.4   17.4     14  115,263
1401  14:27:26  936.3   17.3     73  115,336
1402  14:27:29  936.4   17.4     27  115,363
1403  14:27:32  936.4   17.4      2  115,365
1404  14:27:55  936.7   17.7    357  115,722
1405  14:28:10  937.1   18.1    190  115,912
1406  14:28:26  937.5   18.5    234  116,146
1407  14:28:48  937.5   18.5    276  116,422
1408  14:28:55  937.1   18.1     88  116,510
1409  14:29:07  937.2   18.2     77  116,587
1410  14:29:26  937.2   18.2    363  116,950
1411  14:29:44  937.2   18.2    330  117,280
1412  14:29:50  937.0     18    110  117,390
1413  14:30:15  937.5   18.5    417  117,807
1414  14:45:15  935.1   16.1  3,952  121,759

[1415 rows x 5 columns]

In [7]:
save_path = "/Users/cuong/Documents/VN30F Future Data/VN30F1_" + date[0].replace("/","-") + ".csv"
df.to_csv(save_path,index = False)